packages:
  - apps/*
  - packages/*
  - packages/*/examples/*

catalogMode: strict

catalog:
  '@google-cloud/functions-framework': ^3.0.0
  '@trpc/server': ^11.6.0
  firebase-admin: ^13.0.2
  firebase-functions: ^6.4.0
  zod: ^3.24.1

onlyBuiltDependencies:
  - '@firebase/util'
  - esbuild
  - protobufjs
  - unrs-resolver
